version: "3.7"

services:
  portal:
    container_name: developer_portal
    image: swedbankpay/jekyll-plantuml:2.0.5
    command: serve
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      - .bundle:/usr/local/bundle
