name: Verify Output

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Repository Metadata
      id: repository
      env:
        HEAD_REF: ${{ github.head_ref }}
        REF: ${{ github.ref }}
        EVENT_NAME: ${{ github.event_name }}
        PULL_REPO_NAME: ${{ github.event.pull_request.head.repo.full_name }}
        PULL_REPO_URL: ${{ github.event.pull_request.head.repo.html_url }}
        REPO_NAME: ${{ github.repository }}
      run: ./.github/workflows/repository_metadata.sh

    - name: HTMLProofer
      env:
        GITHUB_BRANCH: ${{ steps.repository.outputs.branch }}
        GITHUB_REPOSITORY_URL: ${{ steps.repository.outputs.url }}
      run: |
        docker-compose \
          -f docker-compose.yml \
          -f .docker/docker-compose.test.yml \
          up \
          --abort-on-container-exit \
          --exit-code-from portal
